config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/faqs',   to: 'static_pages#faqs'

  get '/periodic_table', to: 'p_table#index'

  get '/country_songs', to: 'songs#index'
  resources :country, only: [:show], to: 'songs#show'
  resources :country, only: [:create], to: 'songs#create'

  get '/hiphop_songs', to: 'raps#index'
  resources :hiphop, only: [:show], to: 'raps#show'
  resources :hiphop, only: [:create], to: 'raps#create'

  get    '/fatkat_in',   to: 'sessions#new'
  post   '/fatkat_in',   to: 'sessions#create'
  delete '/fatkat_out',  to: 'sessions#destroy'

  resources :rants

  #currently only being used to test counter function. Refactor.
  get '/word_counter', to: 'word_count#new'
  post '/word_counter', to: 'word_count#create'

  get "/sitemap", to: 'sitemap#index.text'
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil
  def index
    @rap = Rap.all
    @country_songz = Song.all
    @rants = Rant.all
    headers['Content-Type'] = 'application/txt'
    respond_to do |format|
      #format.txt
    end
  end
end
    #respond_to do |format|
      #format.txt { render layout: false }
    #end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/views/sitemap/index.text.erb
  http://www.ricketyrants.com/
  http://www.ricketyrants.com/faqs
  http://www.ricketyrants.com/about
  http://www.ricketyrants.com/contact
  http://www.ricketyrants.com/country/home
  http://www.ricketyrants.com/hiphop/your-love
  http://www.ricketyrants.com/periodic_table?genre=hiphop
  http://www.ricketyrants.com/periodic_table?genre=country
  http://www.ricketyrants.com/rants
  http://www.ricketyrants.com/country/wish-you-were-here
<%# HIPHOP Songs %>
<% Rap.all.each do |song| %>
  <%= hiphop_url(song.slug) %>
<% end %>
<%# Country Songs %>
<% Song.all.each do |song| %>
  <%= country_url(song.slug) %>
<% end %>
<%# RANTS (text messages) %>
<% Rant.all.each do |rant| %>
  <%= rant_url(rant) %>
<% end %>