config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/faqs',   to: 'static_pages#faqs'

  get '/periodic_table', to: 'p_table#index'

  get '/country_songs', to: 'songs#index'
  resources :country, only: [:show], to: 'songs#show'
  resources :country, only: [:create], to: 'songs#create'

  get '/hiphop_songs', to: 'raps#index'
  resources :hiphop, only: [:show], to: 'raps#show'
  resources :hiphop, only: [:create], to: 'raps#create'

  get    '/fatkat_in',   to: 'sessions#new'
  post   '/fatkat_in',   to: 'sessions#create'
  delete '/fatkat_out',  to: 'sessions#destroy'

  resources :rants

  #currently only being used to test counter function. Refactor.
  get '/word_counter', to: 'word_count#new'
  post '/word_counter', to: 'word_count#create'

  get "/sitemap", to: 'sitemap#index.text'
end

app/views/shared/_genre_footer.html.erb
<div class="col-md-12 switch-genre <%= "#{@genre}-theme" %>">
  <h3>
    <%= @genre.capitalize %> Music<br>
  </h3>
  <% if path == "country_lyrics" %>
    <em><%= link_to "(switch to #{@genre_inverse})", hiphop_path(@rap_song) %></em>
  <% elsif path == "hiphop_lyrics" %>
    <em><%= link_to "(switch to #{@genre_inverse})", country_path(@country_song) %></em>

  <% elsif path == "Song_search" %>
    <em><%= link_to "(switch to #{@genre_inverse})", hiphop_songs_path %></em>
  <% elsif path == "Rap_search" %>
    <em><%= link_to "(switch to #{@genre_inverse})", country_songs_path %></em>

  <% elsif path == "periodic_table" %>
    <em><%= link_to "(switch to #{@genre_inverse})", periodic_table_path(genre: @genre_inverse) %></em>
  <% end %>
</div>

app/views/shared/_index.html.erb
<% provide(:title, "#{@genre.capitalize} Search") %>
  <div class="col-md-12 search">
    <%= render partial: 'shared/search_bar', locals: { for_page: 'song_search_one' } %>
  </div>

<% if params[:search] %>
    <% if @search_results.blank? %>
      <div class="col-md-12" id="search-container" >
        <div id="search-not-found">
          <em><%= params[:search] %></em> not found in <%= @genre.capitalize %> Music collection.<br>

        <% unless @lyric_search %>
          <% if @genre == "country" %>
            <%= link_to "(search #{@genre_inverse} music instead)", hiphop_songs_path(search: params[:search]) %>
          <% else %>
            <%= link_to "(search #{@genre_inverse} music instead)", country_songs_path(search: params[:search]) %>
          <% end %>
        <% else %>
          Whoops...not found. <%= link_to "Go Back", url_for(:back) %>
        <% end %>
        </div>

        <div id="search-tips">
          <h3>Search Tips</h3>
          <b>
            Search songs by: Artist, Title, and/or Year<br>
            Search with commas:
              <% if @genre == "country" %>
                "Keith Urban, Toby Keith, Picture to Burn, 2016"
              <% else %>
                "Biggie, Jay Z, Kanye West, 1989, Guilty Conscience"
              <% end %>
            <br>
              To search all Song lyrics, check "Search by Lyrics"
            <br>
            <br>
              Searching lyrics? Less words are better (1 to 3 total)... and check spelling.
          </b>
        </div>
      </div>
    <% else %>

      <div class="search-summary">
        <div id="search-success">
          <%= pluralize(@search_results.uniq.count, 'Song') %> found: <em><%= params[:search].upcase %></em>
        </div>
        <%= link_to "Go to Bottom", '#buttons' %> |
        <%= link_to "Clear Search Results", @genre_search_path %>
      </div>

      <%= form_tag(@genre_post_path, id:"search-results", method: "post") do %>
        <% @search_results.uniq.each do |song| %>
          <% if @genre == "country" %>
            <% genre_show_path = country_path(song) %>
          <% else %>
            <% genre_show_path = hiphop_path(song) %>
          <% end %>
          <div class="search-results">
            <div id="song-results">
              <em>
                <b><%= song.artist %> | <%= link_to song.title, genre_show_path %> (<%= song.year %>) : </b>
                <%= song.lyrics.truncate(100) %>
                <%= link_to "(lyrics)", genre_show_path %>
              </em>
            </div>
            <div id="search-checkbox">
              <%= check_box_tag 'box_ids[]', value = song.id, checked = true, class: "check-size" %>
            </div>
          </div>
        <% end %>
      <% end %>

      <% if @search_results.count > 5 %>
        <div class="search-summary">
          <%= link_to "Go to Top", '#scroll100' %> |
          <%= link_to "Clear Search Results", @genre_search_path %> <br>
          <div id="search-success">
            <%= pluralize(@search_results.uniq.count, 'Song') %> found: <em><%= params[:search].upcase %></em>
          </div>
        </div>
      <% end %>

      <div class="col-xs-12 col-md-6 submit">
        <%= render partial: 'shared/submit_lyric_count', locals: { form: 'search-results'} %>
      </div>
      <div class="col-xs-12 col-md-6 search">
        <%= render partial: 'shared/search_bar', locals: { for_page: "song_index" } %>
      </div>
    <% end %>
<% else %>
    <div class="mizzart">
      <% @comic_cell = [*1..6] %>
      <% @comic_cell.each do |cell| %>
        <div class="col-md-4">
          <%= image_tag "mizz_loves_kitty_pebbles_comic_#{cell}.jpg", class: "img-responsive" %>
        </div>
      <% end %>
    </div>
<% end %>
  <div>
    <%= render partial: 'shared/genre_footer', locals: { path: "#{@song_model}_search" } %>
  </div>

app/views/shared/_output.html.erb
<div class = "panel-group" id = "<%= show %>" >
  <div class = "panel-default">

    <div class="panel-heading">
      <h2 class="dropdown-title  <%= "#{@genre}-theme" %>">
        <a class=<%= "#{@genre}-link" %> data-toggle = "collapse" data-parent = "<%= show %>" href = "#collapse<%= show %>">
          <%= @genre.capitalize %> <%= show.capitalize %>
        </a>
      </h2>
    </div>

    <div id = "collapse<%= show %>" class = "panel-collapse collapse in">
      <div class="song-box DivWithScroll", style="-webkit-overflow-scrolling: touch;">

        <% if show == "words" %>
          <h4>
            <% count_words(@all_lyrics, @output.to_i).each do |word| %>
              <b id="words_output"><%= "#{word.capitalize} | " %></b>
            <% end %>
          </h4>
        <% elsif show == "song-list" %>
          <% @picked_songs.each_with_index do |song, i| %>
            <div id="list-box">
              <div id="list-number">
                <%= "#{i+1}" %>
              </div>
              <div id="list-song">
                <b><%= song.title %> :</b>
                <em><%= song.artist %></em>
                <% if @genre == "hiphop" %>
                  <%= link_to 'Lyrics', hiphop_path(song) %>
                <% else %>
                  <%= link_to 'Lyrics', country_path(song) %>
                <% end %>
              </div>
            </div>
          <% end %>

        <% elsif show == "lyrics" %>
          <%= simple_format(@song.lyrics, class: "lyrics") %>
            <div class="sources">
              Writer(s): <%= @song.writers %> |
              Copyright © <%= @song.copyright %>
            </div>

        <% elsif show == "song" %>
          <div class="song-year">
            <h5>
              <%= @song.year.to_s[0] %><br>
              <%= @song.year.to_s[1] %><br>
              <%= @song.year.to_s[2] %><br>
              <%= @song.year.to_s[3] %>
            </h5>
          </div>

          <div id="song-detail">
            <h3>
              <%= @song.title %><br>
              <em>by <%= @song.artist %></em>
            </h3>

            <div id="song-info">
              <h3>Top 5 Count</h3>
                <% count_words(@song.lyrics, 5).each do |word| %>
                  <b><%= "#{word.capitalize} | " %></b>
                <% end %>
              <br>
              <b>
                <%= raw_count(@song.lyrics) %> Words |
                <%= @percent_unique %>% Unique
              </b>
            </div>

            <div>
              <% if @genre == "country" %>
                <% genre_post_path = country_index_path %>
              <% else %>
                <% genre_post_path = hiphop_index_path %>
              <% end %>
              <%= form_tag(genre_post_path, method: "post") do %>
                <%= hidden_field_tag 'box_ids[]', @song.id %>
                <%= hidden_field_tag :output, 50 %>
                <%= submit_tag 'count this song', class: 'submit', id: 'see-more-button' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="count-summary">
      <% if show == "words" %>
        <%= @word_total %> words -
        <%= @percent_unique %>% unique (<%= @unique_words %>)
      <% elsif show == "song-list" %>
        <%= pluralize(@picked_lyrics.size, 'song') %>
      <% elsif show == "song" %>
        <%= @word_total %> total words
      <% elsif show == "lyrics" %>
        <%= @unique_words %> unique words
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_rant_form.html.erb
<%= simple_form_for(@rant, multipart: true) do |f| %>
  <% if @rant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@rant.errors.count, "error")} prevented success:" %>
      </h2>
      <ul>
        <% @rant.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-12" id="form-group-box">
  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>
    <div id="thumb-attach">
      <p><%= image_tag @rant.image.url %></p>
      <%= f.label :image, "Attach Thumbnail" %>
      <%= f.file_field :image, accept: 'image/jpeg,image/jpg,image/gif,image/png,image/tiff' %>
    </div>
  <div class="form-group custom">
    <%= f.button :submit %>
    <%= link_to "Cancel", :back %>
  </div>
</div>
<% end %>
<%# This javascript raises file-size error on front end ONLY %>
<script type="text/javascript">
  $('#rant_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > .2) {
      alert('Maximum file size is 200KB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search_bar.html.erb
<%# note: @search_path and @show_all_songs in songs helper%>

<%= form_tag(@genre_search_path, method: "get", id: "#{for_page}", class: "search-form" ) do %>
  <em id="search">Search &amp; Count</em><br>
  <%= text_field_tag :search, params[:search], placeholder: " #{@genre} music" %>
  <%= submit_tag "Search", :data => { disable_with: false } %><br>
  <%= check_box_tag "lyric_search", value = '1', checked = @lyric_search_checkbox, form: "#{for_page}" %> <em>Search Lyrics</em> |
  <%= link_to "Show All Songs", @show_all_songs %><br>
  <em id="search-note"> use commas: "artist, artist2, title, year" </em>
<% end %>

app/views/shared/_show.html.erb
<% provide(:title, "#{@genre.capitalize} Songs") %>
    <div id="<%= @genre %>-bkg-pic">
      <div class="col-md-12 scroll-box">
        <ul class="scroll100">
          <%= render partial: 'shared/song_cubes' %>
        </ul>
      </div>
      <div class="col-md-6 song-left">
        <% if @box_ids %>
          <%= render partial: 'shared/output', locals: { show: "song-list" } %>
        <% else %>
          <%= render partial: 'shared/output', locals: { show: "song" } %>
        <% end %>
      </div>
      <div class="col-md-6 song-right" >
        <% if @box_ids %>
          <%= render partial: 'shared/output', locals: { show: "words" } %>
        <% else %>
          <%= render partial: 'shared/output', locals: { show: "lyrics" } %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6 submit">
      <%= render partial: 'shared/submit_lyric_count', locals: { form: 'song-cube'} %>
    </div>
    <div class="col-md-6 search">
      <%= render partial: 'shared/search_bar', locals: { for_page: 'song_show' } %>
    </div>
      <%= render partial: 'shared/genre_footer', locals: { path: "#{@genre}_lyrics" } %>

app/views/shared/_song_cubes.html.erb
<%= form_tag(@genre_post_path, id:"song-cube", method: "post") do %>
  <% @songs.order("id").each do |song| %>
    <% if @genre == "country" %>
      <% genre_show_path = country_path(song, anchor: song.id) %>
    <% else %>
      <% genre_show_path = hiphop_path(song, anchor: song.id) %>
    <% end %>
    <div class="song-cube" id="<%= song.id %>">
      <h5 class="title">
        <%= link_to song.title.truncate(28), genre_show_path %>
      </h5>
      <h6 class= <%= @genre %> >
        <%= song.artist.truncate(17) %>
      </h6>
      <div class="rank">
        #<%= song.rank %>
      </div>
      <div class="check">
        <%= check_box_tag 'box_ids[]', value = song.id, checked = true, class: "check-size" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_submit_lyric_count.html.erb
<div>
  Show:
    <%= radio_button_tag "output", value = 100, checked = true, form: "#{form}" %> 100 words
    <%= radio_button_tag "output", value = 500000, checked = false, form: "#{form}" %> All words
</div>
<div>
  Filter <%= check_box_tag "checkbox", value = "1", checked = false, form: "#{form}" %> remove "and if it etc..."
</div>
<div id="buttons">
  <%= button_tag 'Reset', type: 'reset', id: 'check_all', form: "#{form}" %>
  <%= submit_tag 'Count Lyrics', form: "#{form}", class: 'submit' %>
</div>
<div>

To customize,
  <% if @genre == "hiphop" %>
    <%= link_to "Search & Count", hiphop_songs_path %>
  <% else %>
    <%= link_to "Search & Count", country_songs_path %>
  <% end %>
</div>