config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/faqs',   to: 'static_pages#faqs'

  get '/periodic_table', to: 'p_table#index'

  get '/country_songs', to: 'songs#index'
  resources :country, only: [:show], to: 'songs#show'
  resources :country, only: [:create], to: 'songs#create'

  get '/hiphop_songs', to: 'raps#index'
  resources :hiphop, only: [:show], to: 'raps#show'
  resources :hiphop, only: [:create], to: 'raps#create'

  get    '/fatkat_in',   to: 'sessions#new'
  post   '/fatkat_in',   to: 'sessions#create'
  delete '/fatkat_out',  to: 'sessions#destroy'

  resources :rants

  #currently only being used to test counter function. Refactor.
  get '/word_counter', to: 'word_count#new'
  post '/word_counter', to: 'word_count#create'

  get "/sitemap", to: 'sitemap#index.text'
end

app/models/rant.rb
class Rant < ApplicationRecord
  belongs_to :author
  validates :author_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true
  has_attached_file :image, styles: {
    med: "400x175" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :image, less_than: 200.kilobytes
  #validates :image_file_name, presence: true

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :find_rant, except: [:index, :new, :create]
  before_action :require_login, except: [:show, :index]

  def index
    @rants = Rant.all.order('created_at ASC')
    if params[:page]
    get_page
    else
      @page = 1
    end
    @page_offset = (@page-1) * 6  #(6 texts/page)
  end

  def show
    @rants = Rant.all
  end

  def new
    @rant = Rant.new
  end

  def create
    @rant = current_author.rants.build(rant_params)
    if @rant.save
      flash[:success] = "'#{@rant.title}' successfully saved"
      redirect_to rant_path(@rant)
    else
      flash.now[:danger] = "Error saving new Rant"
      render 'new'
    end
  end

  def destroy
    @rant.destroy
    flash[:success] = "'#{@rant.title}' successfully deleted"
    redirect_to rants_path
  end

  def edit
  end

  def update
    @rant.update(rant_params)
    flash[:success] = "'#{@rant.title}' successfully updated"
    redirect_to rant_path(@rant)
  end

  private

    def rant_params
      params.require(:rant).permit(:title, :body, :image, :data, :author_id) ##ckeditor
    end

    def find_rant
      @rant = Rant.find(params[:id])
    end

    def get_page
      total_pages = (Rant.count/6) + 1
      page_params = params[:page].to_i
      if page_params > 0 && page_params <= total_pages
        @page = page_params
      else
        @page = 1
      end
    end
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/views/rants/_page_turner.html.erb
<div id="prev">
    <%= link_to "Prev Page", rants_path(page: (@page - 1) ) %>
  </div>
  <div id="page">
    <%= @page %>
  </div>
  <div id="next">
    <%= link_to "Next Page", rants_path(page: (@page + 1) ) %>
</div>

app/views/rants/_sidebar.html.erb
<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "PERIODIC TABLE of HIP HOP", periodic_table_path(genre: "hiphop") %>
  </h2>
  <%= link_to image_tag("periodic_table_hiphop_ricketyrants.jpg", class: "img-responsive home-pic", alt: "Periodic Table of Hiphop Lyrics by Ricketyrants"), periodic_table_path(genre: "hiphop") %>
</div>

<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "HIP HOP COUNTER - Lyrics", hiphop_path(@rap_song.id) %>
  </h2>
  <%= link_to image_tag("lyrics_calculator_hiphop_ricketyrants.jpg", class: "img-responsive home-pic", alt: "Stacked Money being machine counted like hiphop lyrics"), hiphop_path(@rap_song.id) %>
</div>

<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "PERIODIC TABLE of COUNTRY", periodic_table_path(genre: "country") %>
  </h2>
  <%= link_to image_tag("periodic_table_country_ricketyrants.jpg", class: "img-responsive home-pic", alt: "Periodic Table of Country Music Lyrics by Ricketyrants"), periodic_table_path(genre: "country") %>
</div>

<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "COUNTRY COUNTER - Lyrics", country_path(@country_song.id) %>
  </h2>
  <%= link_to image_tag("lyrics_calculator_country_music_ricketyrants.jpg", class: "img-responsive home-pic", alt: "Stacked Money being machine counted like country music lyrics"), country_path(@country_song.id) %>
</div>

<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "THE RANTS", rants_path %>
  </h2>
  <%= link_to image_tag("ricketyrants_country_rap_dichotomy.jpg", class: "img-responsive home-pic", alt: "Hiphop and Country Music Dichotomy"), rants_path %>
</div>

<div class="home-cubes rant-sidebar">
  <h2>
    <%= link_to "COMMENTS", rants_path %>
  </h2>
  <%= link_to image_tag("comments_country_rap_ricketyrants.jpg", class: "img-responsive home-pic", alt: "Hiphop and Country Music Dichotomy"), rants_path %>
</div>

app/views/rants/_text_preview.html.erb
<% unless @rants[rant].nil? %>
  <h2>
    <%= link_to @rants[rant].title.truncate(35), rant_path(@rants[rant]) %>
  </h2>
  <div class="rant-thumb">
    <%= link_to image_tag(@rants[rant].image, class: "img-responsive"), rant_path(@rants[rant]) %>
  </div>
<% else %>
  <%= image_tag("ricketyrants_dizz_dog1_blue.jpg", class: "img-responsive blue_mizz_pics", alt: "Bro-chick text message") %>
<% end %>

app/views/rants/edit.html.erb
<% provide(:title, @rant.title) %>

  <%= render partial: 'shared/rant_form' %>

app/views/rants/index.html.erb
<% provide(:title, 'The Rants') %>
<% provide(:format, 'index') %>

<div class="prev-next-mobile">
  <%= render partial: 'rants/page_turner' %>
</div>

<div class="row">
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (0 + @page_offset) } %>
  </div>
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (1 + @page_offset) } %>
  </div>
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (2 + @page_offset) } %>
  </div>
</div>

<div class="row">
  <div class="col-md-3 home-cubes">
    <div>
      <%= image_tag("ricketyrants_mizz_cat#{@page}_blue_inverse.jpg", class: "img-responsive", alt: "rickety_rants_mizzart") %>
    </div>
  </div>
  <div class="col-md-6 home-cubes">
    <%= image_tag("ricketyrants_logo.gif", class: "img-responsive", id: "logo-rants", alt: "RicketyRants Logo") %>
    <div>
      <%= render partial: 'rants/page_turner' %>
    </div>
  </div>
  <div class="col-md-3 home-cubes">
    <%= image_tag("ricketyrants_mizz_cat#{@page}_blue.jpg", class: "img-responsive", alt: "Bro-chick text message") %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (3 + @page_offset) } %>
  </div>
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (4 + @page_offset) } %>
  </div>
  <div class="col-md-4 home-cubes">
    <%= render partial: 'rants/text_preview', locals: { rant: (5 + @page_offset) } %>
  </div>
</div>

<div class="prev-next-mobile">
  <%= render partial: 'rants/page_turner' %>
</div>

app/views/rants/new.html.erb
<% provide(:title, 'Create Rant') %>
  <div class="background-image">
    <%= render partial: 'shared/rant_form' %>
  </div>

app/views/rants/show.html.erb
<% provide(:title, @rant.title) %>
<% provide(:format, 'sidebar') %>

<div class="nav-spacer"></div>
  <div>
    <div class="rant-content col-xs-12 col-sm-8 col-md-8 DivWithScroll">
      <div class="rant-header">
        <h2><%= @rant.title %></h2>
        <%= link_to "(see all rants)", rants_path %>
      </div>
      <div id="rant-body">
        <%= raw @rant.body %>
      </div>
      <div class="rant-header">
        <%= link_to "Back to All Rants", rants_path %>
        <% if logged_in? %>
          | <%= link_to "Delete Post", rant_path(@rant), method: :delete, data: {confirm: "Really delete post?"} %>
          | <%= link_to "Edit Rant", edit_rant_path(@rant) %>
        <% end %>
      </div>
    </div>
    <div class="sidebar col-sm-4 col-md-4 DivWithScroll">
      <%= render partial: 'sidebar' %>
    </div>
  </div>
  <h2 class="col-md-12 rant-header" id="scroll-header">More Rants</h2>
  <div class="col-md-12 scroll-box" id="rant-scroll">
    <ul class="scroll100">
      <% @rants.each do |rant| %>
        <div class="rant-cube">
          <%= link_to rant.title, rant_path(rant) %>
          <%= link_to image_tag(rant.image, class: "img-responsive"), rant_path(rant) %>
        </div>
      <% end %>
    </ul>
  </div>