config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'


  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/faqs',   to: 'static_pages#faqs'

  get '/periodic_table', to: 'p_table#index'

  get '/country_songs', to: 'songs#index'
  resources :country, only: [:show], to: 'songs#show'
  resources :country, only: [:create], to: 'songs#create'

  get '/hiphop_songs', to: 'raps#index'
  resources :hiphop, only: [:show], to: 'raps#show'
  resources :hiphop, only: [:create], to: 'raps#create'

  get    '/fatkat_in',   to: 'sessions#new'
  post   '/fatkat_in',   to: 'sessions#create'
  delete '/fatkat_out',  to: 'sessions#destroy'

  resources :rants

  #currently only being used to test counter function. Refactor.
  get '/word_counter', to: 'word_count#new'
  post '/word_counter', to: 'word_count#create'

  get "/sitemap", to: 'sitemap#index.text'
end

app/views/layouts/_flash_message.html.erb
<div>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to image_tag("rails.png", alt: "ruby on rails logo"), 'http://rubyonrails.org/' %></li>
      <li><%= image_tag(asset_path("logo_scratchy.jpg"), alt: "scratchy logo") %></li>
      <li class="hide-mobile" style="font-size: .75em;">© 2017 All Rights Reserved.</li>
      <span class="foot-link">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li class="hide-mobile">
          <%= link_to "Contact", contact_path %>
        </li>
        <li class="hide-mobile">
          <%= link_to "About", about_path %>
        </li>
      </span>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <nav class="container" id="nav-container">
    <div class="col-xs-9 nav-left">
      <%= link_to "RicketyRants", root_path, id: "nav_logo" %>
        <h5>A place of elegant irreverence</h5>
    </div>
    <div class="col-xs-3 nav-right">
      <ul id="nav-list" class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="dropdown-toggle" data-toggle="dropdown"><span>|||||||</span> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" id="dropdown-menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "The Rants", rants_path %></li>
              <em></em>
                <li><%= link_to "HipHop Counter - Lyrics", hiphop_path(@rap_song) %></li>
                <li><%= link_to "Periodic Table of Hip Hop", periodic_table_path(genre: "hiphop") %></li>
              <em></em>
                <li><%= link_to "Country Counter - Lyrics", country_path(@country_song) %></li>
                <li><%= link_to "Periodic Table of Country", periodic_table_path(genre: "country") %></li>
              <em></em>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <li><%= link_to "FAQs", faqs_path %></li>
            <% if logged_in? %>
              <li class="divider">
              </li>
              <li id="new-rant">
                <%= link_to "NEW RANT", new_rant_path %>
              </li>
              <li>
                <%= link_to "Log Out", fatkat_out_path, method: "delete" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <div class="container" id="container-size">
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>